import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import UserProvider from "@/provider/userProvider";
import { initialUser } from "@/lib/shared/initialState";
import { ENV } from "@/lib/server/Errors/env";
import reducer from "@/contexts/Reducer";
import { QueryClient } from "@tanstack/react-query";
import { getUserFromSession } from "@/lib/server/layers/actions/authActions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/icon.png",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let authenticatedUser = initialUser;

  try {
    /* authenticatedUser = await getUserFromSession(); */
  } catch (error) {
    // User not authenticated or session expired
    console.log("No valid session");
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <UserProvider User={authenticatedUser} reduce={reducer}>
          <Header />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
