import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import UserProvider from "@/provider/userProvider";
import reducer from "@/contexts/Reducer";
import { getUserFromSession } from "@/lib/server/layers/actions/authActions";
import { initialUser } from "@/lib/shared/initialState";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: "/icon.png",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user;
  try {
    user = await getUserFromSession();
  } catch (error) {
    /* if (error instanceof AccessTokenNeedRefreshError) {
      try {
        await refreshAccessToken();
      } catch (refreshError) {
        throw new Error("Failed to refresh access token: " + refreshError);
      }
      try {
        user = await getUserFromSession();
      } catch (getUserError) {
        user = initialUser;
      }
    } else {
      user = initialUser;
    } */
    user = initialUser;
  }
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-white`}
      >
        <UserProvider User={user} reduce={reducer}>
          <Header />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
